nginx:
    image: tutum/nginx
    ports:
        - "80:80"
    links:
        - phpfpm
    volumes:
        - ../../docker/vhost.conf:/etc/nginx/sites-available/default
        - ../../docker/vhost.conf:/etc/nginx/sites-enabled/default

        - ./storage/logs/nginx-error.log:/var/log/nginx/error.log
        - ./storage/logs/nginx-access.log:/var/log/nginx/access.log
phpfpm:
    image: php:fpm
    ports:
        - "9000:9000"
    volumes:
        - ./:/var/www/iqra
mysql:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: admin
  ports:
    - "3306:3306" 
